# Warp Restriction - needed levels to be able to create a warp
# 0 or negative values will disable this restriction
# 10 is default
warplevelrestriction: 10

# Text that player must put on sign to make it a warp sign
# Not case sensitive!
welcomeLine: [WELCOME]

# This list stores GameModes in which Challenges addon should not work.
# To disable addon it is necessary to write its name in new line that starts with -. Example:
# disabled-gamemodes:
#  - BSkyBlock
disabled-gamemodes: []